### ISSUE TITLE
Id de ordem de serviço duplicado

### ISSUE THREAD

**Issue by leonardovalverde** [tractian/fake-api#4]
Existem duas ordens de serviço com o `id: 2`, ids são únicos e isso gera um problema na hora de buscar uma ordem de serviço pelo id. É uma correção simples de se fazer :)

**Comment by igmarinelli** [comment]
@leonardovalverde Pode corrigir e mandar um pullrequest?

**Comment by leonardovalverde** [comment]
@igmarinelli https://github.com/tractian/fake-api/pull/5
